# Generated by Django 3.0.7 on 2020-06-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200623_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.CharField(default='', max_length=20, verbose_name='عرض جغرافیایی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.CharField(default='', max_length=20, verbose_name='طول جغرافیایی'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
