# Generated by Django 3.0.7 on 2020-06-26 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_auto_20200626_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
